echo "" > Account.cpp
echo "" > Account.h
echo "" > main.cpp
echo "" > Savings_Account.cpp
echo "" > Savings_Account.h
echo "" > Accout_Util.cpp
echo "" > Account_Util.h
echo "" > Checking_Account.cpp
echo "" > Checking_Account.h
echo "" > Trust_Account.cpp
echo "" > Trust_Account.h
