echo #include >> Account.cpp
echo #include >> Account.h
echo #include >> Account_Util.cpp
echo #include >> Account_Util.h
echo #include >> Checking_Account.cpp
echo #include >> Checking_Account.h
echo #include >> I_Printable.cpp
echo #include >> I_Printable.h
echo #include >> main.cpp
echo #include >> Savings_Account.cpp
echo #include >> Savings_Account.h
echo #include >> Trust_Account.cpp
echo #include >> Trust_Account.h
